name: ML Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest test_ml_pipeline.py

    - name: Train model
      run: |
        python ml_pipeline.py

    - name: Upload model artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: trained-model
        path: random_forest_model.joblib
